### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Eclipse_workplace/web_tensorflow/cut_sentence_corpus.txt'

### ISSUE THREAD

**Issue by 071Kady** [Chriszhangmw/Clinical-decision-support-system#1]
I have not this files.How to get this files?

(Clinical) D:\lab\LABprogram\Clinical-decision-support-system-master\web_demo\working>python test.py
2021-01-26 15:25:47.402749: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from model_run import first_action, record_sample
  File "D:\lab\LABprogram\Clinical-decision-support-system-master\web_demo\working\model_run.py", line 7, in <module>
    from sentence_cut import cut_non
  File "D:\lab\LABprogram\Clinical-decision-support-system-master\web_demo\working\sentence_cut.py", line 11, in <module>
    with open(path1,'r',encoding='utf-8') as v:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Eclipse_workplace/web_tensorflow/cut_sentence_corpus.txt'

**Comment by nikhilreddy2004** [comment]
Hi, Kady can you please guide me on how to run this project and I am a little new to this.
